name = "bun-hit-counter"
compatibility_date = "2025-09-19"
# Where the built React site lives
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "HIT_COUNTER"
id = "cd5920f8d60e48588a2f46591907bedb"
